name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nodejs version
        run: node -v 

      - name: npm version
        run: npm -v
        
      - name: install tool
        run: |
          npm install
          
      - name: build static
        run: |
          npm run build
          
      - name: Upload to static-web
        uses: actions/upload-artifact@v4
        with:
          name: static-web
          path: dist/*
